### ISSUE TITLE
Cannot use output='bulk'

### ISSUE THREAD

**Issue by catalandres** [mneedham91/PyPardot4#11]
Trying this:
```
p.visits.query_by_prospect_ids(
             prospect_ids=prospect,
             sort_by='created_at',
             sort_order='ascending',
             output='bulk')
```
returns this:
```
File "/usr/local/lib/python3.6/site-packages/pypardot/objects/visits.py", line 51, in query_by_prospect_ids
    if result['total_results'] == 0:
KeyError: 'total_results'
```

As per [Pardot's documentation](http://developer.pardot.com/#changing-the-api-response-format), this option _"returns basic data for an object (does not provide total object count). Used for querying large amounts of data."_

If the option `output='bulk'` is entered, the code should not rely in the return of the key `total_results`, because it won't be there.

**Comment by mneedham91** [comment]
This was resolved in latest commit thanks to @swkasula

**Comment by zhar97** [comment]
I noticed that @mneedham91 has declared this issue closed after @swkasula's latest commit. But, I still encountered the problem.
